/**
 * The link types of the GS1 Web vocabulary, as GS1 publishes them at
 * https://ref.gs1.org/voc/data/linktypes: sixty terms, one of them, `productSustainabilityInfo`,
 * marked deprecated there and kept here because a client can still ask for it.
 *
 * Held so that a type a caller asks for is recorded only when it is one of these, and not when it
 * merely has the shape of one: by shape, `gs1:JohnSmith19800101` went into the log as the type
 * asked for. A term GS1 adds later is recorded once an identifier's links carry it, and not before.
 */
export const GS1_LINK_TYPES: ReadonlySet<string> = new Set([
  "activityIdeas",
  "allergenInfo",
  "appDownload",
  "backgroundInfo",
  "brandHomepageClinical",
  "brandHomepagePatient",
  "careersInfo",
  "certificationInfo",
  "consumerHandlingStorageInfo",
  "defaultLink",
  "defaultLinkMulti",
  "dpp",
  "eifu",
  "epcisRepository",
  "epil",
  "eventsInfo",
  "faqs",
  "handledBy",
  "hasRetailers",
  "homepage",
  "ingredientsInfo",
  "instructions",
  "jws",
  "leaveReview",
  "locationInfo",
  "logisticsInfo",
  "loyaltyProgram",
  "masterData",
  "menuInfo",
  "nutritionalInfo",
  "openingHoursInfo",
  "paymentLink",
  "pip",
  "productSustainabilityInfo",
  "promotion",
  "purchaseSuppliesOrAccessories",
  "quickStartGuide",
  "recallStatus",
  "recipeInfo",
  "registerProduct",
  "registryEntry",
  "relatedImage",
  "relatedVideo",
  "reportFound",
  "review",
  "safetyInfo",
  "scheduleTime",
  "serviceInfo",
  "smartLabel",
  "smpc",
  "socialMedia",
  "statisticInfo",
  "subscribe",
  "support",
  "sustainabilityInfo",
  "traceability",
  "tutorial",
  "userAgreement",
  "verificationService",
  "whatsInTheBox",
]);
