/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes one published experience: the physical thing it belongs to, the targets that recognise it, and the content anchored to each target.
 */
export interface TaggantExperienceManifest {
  schemaVersion: "1.0.0";
  id: string;
  title?: string;
  subject?: {
    kind?: "product" | "print" | "artwork" | "other";
    reference?: string;
  };
  /**
   * @minItems 1
   */
  targets: [Target, ...Target[]];
  fallback?: string;
}
export interface Target {
  id: string;
  source: string;
  physicalWidthMm: number;
  /**
   * @minItems 1
   */
  content: [Content, ...Content[]];
}
export interface Content {
  type: "image" | "video" | "model" | "audio";
  src: string;
  placement?: Placement;
  autoplay?: boolean;
  loop?: boolean;
  muted?: boolean;
}
export interface Placement {
  scale?: number;
  offsetX?: number;
  offsetY?: number;
  rotationDeg?: number;
}
